package(default_visibility = ["//visibility:public"])

# Emulate the result of a cargo_compile
filegroup(
    name = "precompiled_crate",
    srcs = [
        "liburl-bc832e9c02aa9658.rlib",
        "liblibc-cabc0b1c3e605328.rlib"
    ]
)
